project: 
  type: website
  output-dir: docs

website: 
  title: Analiza danych w czasie rzeczywistym
  navbar:
    left: 
          - href: indexD.qmd
            text: 222890-D
          - href: indexS.qmd
            text: 222890-S
          - href: sylabus.qmd
            text: Sylabus
          - href: ksiazki.qmd
            text: Książki

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    self-contained-math: true