---
title: "Informacje ogólne"
---

## Analiza danych w czasie rzeczywistym

Kod: 222890-S

Semestr zimowy 2022/2023,
SGH Szkoła Główna Handlowa w Warszawie

Szczegółowy opis znajdziesz w [sylabusie](/RTA_2023/sylabus).
Znajdziesz w nim opis wszystkich wykładów i ćwiczeń oraz proponowaną literaturę.

Inne książki zamieszczone zostały w zakładce [książki](/RTA_2023/ksiazki)

## Kalendarz

1. 25-02-2023 (sobota) 08:00-09:30 - Wykład 1
2. 11-03-2023 (sobota) 08:00-09:30 - Wykład 2

3. 20-03-2022 (poniedziałek) 08:00-13:30 - Cwiczenia 1, 3 grupy


...

#### Miejsce

Wykłady 1-2: G-Aula IV
Laboratorium 1-5: 116 G

#### Zaliczenie i Egzamin


Wykłady zakończone zostaną teste (ostatnie zajęcia).
Pozytywna ocena z testu (powyżej 13 pkt) upoważnia do realizacji ćwiczeń. 

Na ćwiczeniach realizowane będą zadania do wykonania - za pośrednictwem platformy teams. 
Zaliczenie wszystkich ćwiczeń upoważnia do realizacji projektu. 

Projekt powinien być realizowany w grupach max 5 osobowych. 

Wymagania projektu: 

- Projekt powinien przedstawiać BIZNESOWY PROBLEM, który można realizować wykorzystując informacje podawane w trybie online. (Nie oznacza to, że nie można korzystać z procesowania batchowego np w celu wygenerowania modelu).
- Dane powinny być przesyłane do Apache Kafki i stamtąd poddawane dalszemu procesowaniu i analizie. 
- Język programowania jest dowolny - dotyczy każdego komponentu projektu. 
- można wykorzystać narzędzia BI 
- żródłem danych może być tabela, sztucznie generowane dane, IoT itp.


## Technologie

1. [GIT](https://sebkaz-teaching.github.io/RTA_2023/GIT/)
2. Python, Jupyter notebook, Jupyter lab, Colab
3. [Docker](https://sebkaz-teaching.github.io/RTA_2023/Docker/)
4. **Apache Spark**, Apache Flink, **Apache Kafka**, Apache Beam
5. Databricks Community edition [Web page](https://community.cloud.databricks.com/login.html).
