---
title: "Informacje ogólne"
---

## Analiza danych w czasie rzeczywistym

Kod: 222890-D

Semestr zimowy 2022/2023,
SGH Szkoła Główna Handlowa w Warszawie

Szczegółowy opis znajdziesz w [sylabusie](/RTA_2023/sylabus).
Znajdziesz w nim opis wszystkich wykładów i ćwiczeń oraz proponowaną literaturę.

Inne książki zamieszczone zostały w zakładce [książki](/RTA_2023/ksiazki)

## Kalendarz

1. 20-02-2023 (poniedziałek) 09:50-11:30 - Wykład 1
2. 27-02-2023 (poniedziałek) 09:50-11:30 - Wykład 2
3. 06-03-2023 (poniedziałek) 09:50-11:30 - Wykład 3
4. 13-03-2023 (poniedziałek) 09:50-11:30 - Wykład 4
5. 20-03-2023 (poniedziałek) 09:50-11:30 - Wykład 5

6. 20-03-2022 (poniedziałek) 08:00-13:30 - Cwiczenia 1, 3 grupy
6. 21-03-2022 (wtorek) 11:40-17:00 - Cwiczenia 1, 3 grupy  
7. 27-03-2022 (poniedziałek) 08:00-13:30 - Cwiczenia 2, 3 grupy
7. 28-03-2022 (wtorek) 11:40-17:00 - Cwiczenia 2, 3 grupy
8. 03-04-2022 (poniedziałek) 08:00-13:30 - Cwiczenia 3, 3 grupy
8. 04-04-2022 (wtorek) 11:40-17:00 - Cwiczenia 3, 3 grupy 

...

#### Miejsce

Wykłady 1-5: G-Aula I
Laboratorium 1-9: C-4D

#### Zaliczenie i Egzamin

Od pierwszych zajęc studenci organizują grupy projektowe (max. 5 osób) do realizacji projektu w ramach przedmiotu.

Tutaj dodać dokładniejszy opis...

## Technologie

1. [GIT](https://sebkaz-teaching.github.io/RTA_2023/GIT/)
2. Python, Jupyter notebook, Jupyter lab, Colab
3. [Docker](https://sebkaz-teaching.github.io/RTA_2023/Docker/)
4. **Apache Spark**, Apache Flink, **Apache Kafka**, Apache Beam
5. Databricks Community edition [Web page](https://community.cloud.databricks.com/login.html).
